displayName: Keycloak Introspect
type: middleware

import: github.com/gordonlukch/Keycloak-Introspect

summary: "Keycloak Introspect"

testData:
  hostname: "keyclock hostname"
  client_id: "xxxxxxxxxx"
  client_secret: "xxxxxxxxxx"
  realm: "xxxxxxxxxx"
